### PR TITLE
Add support for Apple Silicon Macs

### PR DESCRIPTION
**Pull request by malob**

### CODE REVIEW

**Comment by zimbatm** [comment]
I had to revert this PR because it was failing the `nix flake check` test

**Comment by zimbatm** [comment]
I suspect that nix/nixpkgs.nix needs to be bumped at a version that supports aarch64

**Comment by malob** [comment]
Should I go head and do that?

**Comment by zimbatm** [comment]
yes, if you submit a fixed PR I will happily merge it.

**Comment by malob** [comment]
Great, see #156.

**Pull request merged**
