### PR TITLE
remove the CLI

### PR DESCRIPTION
**Pull request by zimbatm**
The CLI is just another thing to install and that makes the bootstrapping process longer. It also doesn't do much aside being yet another frontend to Nix. Just use flakes.

### CODE REVIEW

**Review by brianmcgee — APPROVED** [review]
LGTM

**Comment by brianmcgee** [comment]
bors merge

**Comment by Mic92** [comment]
bors merge

**Comment by zimbatm** [comment]
bors merge

**Comment by zimbatm** [comment]
bors merge

**Pull request merged**
